name: CMake

on:
  push:
    # paths:
    # - .github/workflows/cmake.yml
  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.) 
  BUILD_TYPE: retail
  VERSION: RC

jobs:
  linux-build:
    uses: ./.github/workflows/cmake_linux_x64.yml
    with: 
      build-type: ${{github.env.BUILD_TYPE}}
      version: ${{github.env.VERSION}}
  windows-build:
    uses: ./.github/workflows/cmake_windows_x64.yml
    with: 
      build-type: ${{github.env.BUILD_TYPE}}
      version: ${{github.env.VERSION}}
  windows-32-bit-build:
    uses: ./.github/workflows/cmake_windows_x64.yml
    with: 
      build-type: ${{github.env.BUILD_TYPE}}
      version: ${{github.env.VERSION}}
  make-release:
    needs: [ linux-build, windows-build, windows-32-bit-build ]
    runs-on: ubuntu-latest
    steps:
    - name: Get log messages
      id: messages
      run: echo "git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:-%s"
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%s')"
    - name: Make release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ steps.date.outputs.date }}
        release_name: DOOM BFA Nigthly ${{ steps.date.outputs.date }}
        body: |
          ${{ steps.messages.outputs.messages }}
        draft: false
        prerelease: true
    - name: Upload Linux Production Artifact
      uses: ./.github/actions/package_formatter
      with:
        artifact_name: linux-${{env.VERSION}}-${{env.BUILD_TYPE}}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        commands: |
          mv ./build/DoomBFA DoomBFA
          mv ./base/DoomBFA.sh DoomBFA.sh
          mv ./build/vcpkg_installed/x64-linux/share/* ./third-party-licenses
          chmod +x DoomBFA
          chmod +x DoomBFA.sh
    - name: Upload Linux Debug Artifact
      uses: ./.github/actions/package_formatter
      with:
        artifact_name: linux-${{env.VERSION}}-debug
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        commands: |
          mv ./build/DoomBFA DoomBFA
          mv ./base/DoomBFA.sh DoomBFA.sh
          mv ./build/vcpkg_installed/x64-linux/share/* ./third-party-licenses
          chmod +x DoomBFA
          chmod +x DoomBFA.sh
    - name: Upload x64 Windows Production Artifact
      uses: ./.github/actions/package_formatter
      with:
        artifact_name: windows-${{env.VERSION}}-${{env.BUILD_TYPE}}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        commands: |
          mv ./build/${{env.BUILD_TYPE}}/* .
          mv ./build/vcpkg_installed/x64-windows-static-md/share/* ./third-party-licenses
    - name: Upload x64 Windows Debug Artifact
      uses: ./.github/actions/package_formatter
      with:
        artifact_name: windows-${{env.VERSION}}-debug
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        commands: |
          mv ./build/retwithdebugsymbols/* .
          mv ./build/vcpkg_installed/x64-windows-static-md/share/* ./third-party-licenses
    - name: Upload x86 Windows Production Artifact
      uses: ./.github/actions/package_formatter
      with:
        artifact_name: windows-${{env.VERSION}}-${{env.BUILD_TYPE}}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        commands: |
          mv ./build/${{env.BUILD_TYPE}}/* .
          mv ./build/vcpkg_installed/x86-windows-static-md/share/* ./third-party-licenses
